# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

conda:
  environment: doc/rtd-environment.yml

python:
  install:
    - method: pip
      path: .[full]

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true